// File generated by FlutterFire CLI or manual configuration.
// Replace the placeholder values with your Firebase project credentials.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your FlowCycle Firebase project.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDETnFVMEf-lLTyap7JLBGSbFmAyoEeo6g',
    appId: '1:1011663589978:web:b4cebe142d0dc4f51fbe63',
    messagingSenderId: '1011663589978',
    projectId: 'flowcycle-app',
    authDomain: 'flowcycle-app.firebaseapp.com',
    storageBucket: 'flowcycle-app.firebasestorage.app',
    measurementId: 'G-BX1FLMSKPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPNZHOTq7XKSzNcc-Zuok4BikEFKpX2FA',
    appId: '1:1011663589978:android:32973c3468b8b9e71fbe63',
    messagingSenderId: '1011663589978',
    projectId: 'flowcycle-app',
    storageBucket: 'flowcycle-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU85vWW2E89T8BSqIbBO47-zv7yYKFFC0',
    appId: '1:1011663589978:ios:4a22d26e5586fa191fbe63',
    messagingSenderId: '1011663589978',
    projectId: 'flowcycle-app',
    storageBucket: 'flowcycle-app.firebasestorage.app',
    iosClientId: '1011663589978-34qu1blc8t8k1d99qtp22jiuns3o2n79.apps.googleusercontent.com',
    iosBundleId: 'com.flowcycle.flowcycle',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDemoFlowCycleMacKeyPlaceholder',
    appId: '1:1234567890:ios:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'flowcycle-app',
    storageBucket: 'flowcycle-app.appspot.com',
    iosBundleId: 'com.flowcycle.flowcycle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDemoFlowCycleWindowsKeyPlaceholder',
    appId: '1:1234567890:web:abcdef123456',
    messagingSenderId: '1234567890',
    projectId: 'flowcycle-app',
    authDomain: 'flowcycle-app.firebaseapp.com',
    storageBucket: 'flowcycle-app.appspot.com',
  );
}
